[package]
rust-version.workspace = true
name = "sdkwork-api-browser-standalone-gateway"
description = "HTTP API server for SDKWork Browser app-api and backend-api surfaces."
version.workspace = true
edition.workspace = true
license.workspace = true


[[bin]]
name = "sdkwork-api-browser-standalone-gateway"
path = "src/main.rs"

[dependencies]
sdkwork-api-browser-assembly.workspace = true
axum.workspace = true
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
sdkwork-iam-web-adapter = { workspace = true }
sdkwork-web-bootstrap = { workspace = true }



[lints]
workspace = true