[package]
rust-version.workspace = true
name = "sdkwork-routes-browser-backend-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "SDKWork Browser backend-api route manifest."


[lints]
workspace = true
[lib]
path = "src/lib.rs"

[dependencies]
sdkwork-web-core.workspace = true
sdkwork-web-axum.workspace = true
sdkwork-iam-web-adapter.workspace = true
sdkwork-routes-browser-support.workspace = true
sdkwork-browser-platform-service.workspace = true
sdkwork-utils-rust.workspace = true
axum.workspace = true
tokio.workspace = true

[dev-dependencies]
sdkwork-web-core.workspace = true
